version: '3'
services:
  reverseproxy:
    build:
      context: .
    image: kafuuma/reverseproxy
  backend_user:
    build:
      context: ../../api-user
    image: kafuuma/udacity-restapi-user
  backend_feed:
    build:
      context: ../../api-feed
    image: kafuuma/udacity-restapi-feed
  frontend:
    build:
      context: ../../frontend
    image: kafuuma/udacity-frontend:local
